version: '3'
services:
  api:
    image: node:12.18.4
    ports:
      - 3000:3000
    environment:
      - DB_CONNECTION=mongodb://pokies-admin:pokies-pass@db:27017
      - DB_NAME=pokies
    volumes:
      - type: bind
        source: ./Server
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
    depends_on: 
      - db
  db:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=pokies-admin
      - MONGO_INITDB_DATABASE=pokies
      - MONGO_INITDB_ROOT_PASSWORD=pokies-pass
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./Server/db/seed.js:/docker-entrypoint-initdb.d/seed.js:ro"
      # - "./db/seed.js:/docker-entrypoint-initdb.js/seed.js:ro"
volumes:
  dbdata: